---
title: "acs_lab3"
author: "Nicholas Baetge"
date: "7/21/2021"
output: github_document
---

# Load Libraries

```{r setup}
library(tidyverse)
library(readxl)
library(ggpubr)
library(fs)
library(lubridate)
```


# Import Data

```{r}
#save filenames that are in the folder of interest
csv_files <- fs::dir_ls("~/GITHUB/oceanoptics2021/data/acs94_lab3_721/", regexp = "\\.csv$")
```


```{r}
#the first two rows of the acs data output contain header and unit data. we'll store those separately...units first and we'll circle back to headers
units <- colnames(read_csv(csv_files[1], skip = 1))

#extract the wavelengths from the "a" column and store as a vector (these are also the same for c)
wavelengths <- units[4] %>% strsplit(., split = " ") %>% .[[1]] %>%  str_remove(., "1/m	lambda=") 
   
#store all data from all files one data frame (this is what the map_dfr function does). We'll add the filenames to the dataframe as well, in a column called "source. 
data <- csv_files %>% 
  map_dfr(read.csv, skip = 2, header = F, .id = "source") %>% 
  #shorten the filenames
  mutate(source = gsub("/Users/nicholasbaetge/GITHUB/oceanoptics2021/data/", "", source),
         source = gsub(".csv", "", source)) %>% 
  #add some distinguisihing metadata about the filenames 
  mutate(sample = ifelse(source == "acs94_lab3_721/ACS94_20210721_175023", "a cal 1", NA),
        sample = ifelse(source == "acs94_lab3_721/DIW_ACS94_20210721_175625", "a cal 2", sample),
        sample = ifelse(source == "acs94_lab3_721/DIW_ACS94_20210721_180208", "c cal 1", sample),
        sample = ifelse(source == "acs94_lab3_721/DIW_ACS94_20210721_180545", "c cal 2", sample),
        sample = ifelse(source == "acs94_lab3_721/DIW_ACS94_20210721_180956", "c cal 3", sample),
        
           sample = ifelse(source ==  "acs94_lab3_721/DIW_ACS94_20210721_181513", "a filtrate", sample),
        sample = ifelse(source ==  "acs94_lab3_721/DIW_ACS94_20210721_181649", "c filtrate", sample),
        sample = ifelse(source ==  "acs94_lab3_721/DIW_ACS94_20210721_182207", "c whole", sample),
        sample = ifelse(source ==  "acs94_lab3_721/DIW_ACS94_20210721_182414", "a whole", sample),
        
        sample = ifelse(source ==  "acs94_lab3_721/DIW_ACS94_20210721_183400", "a cal 4", sample),
         sample = ifelse(source == 
        "acs94_lab3_721/DIW_ACS94_20210721_183439", "unknown", sample),
      
         sample = ifelse(source ==  "acs94_lab3_721/DIW_ACS94_20210721_184004", "a cal 5", sample),
        sample = ifelse(source ==  "acs94_lab3_721/DIW_ACS94_20210721_185427", "c cal 6", sample),
     
        sample = ifelse(source ==  "acs94_lab3_721/DIW_ACS94_20210721_184637", "discrete a filtrate", sample),
        sample = ifelse(source ==  "acs94_lab3_721/DIW_ACS94_20210721_185739", "discrete c filtrate", sample),
        
        
        
                    ) %>%
  select(source, sample, everything())

#add the headers to the dataframe
headers <- c("source", "sample", colnames(read_csv(csv_files[1])))
colnames(data) <-  headers

```

# a


```{r}
#extract the a-tube data and separate out the data
a <- data %>% 
  select(a) %>% 
  #there are sometimes one, two, or three spaces between the data. str_squish helps us deal with that
  mutate(a = str_squish(a)) %>% 
  #remove the brackets
  mutate(a = str_replace_all(a, "\\[|\\]", "")) %>%
  mutate(a = str_squish(a)) %>% 
  separate(a, sep = " ", into = wavelengths) %>% 
  mutate_all(as.numeric)
  
```


```{r}
#combine a data with metadata and change data classes
a_data <- bind_cols(data, a) %>% 
  select(-c, -a) %>% 
  mutate(time = ymd_hms(time)) %>% 
  group_by(source) %>% 
   mutate(interv = interval(first(time), time),
         s = as.numeric(interv),
         min = s/60) %>% 
  select(source:time, interv:min, everything()) %>% 
  ungroup() 
```

## medians and se

```{r}
#calculate medians for each wavelength
a_med <- a_data %>% 
  select(source:sample, c(11:91)) %>% 
  group_by(source) %>% 
  mutate_at(c(3:83), list(med = median)) %>% 
  ungroup() %>% 
  select(source:sample, contains("med")) %>% 
  distinct() %>% 
  rename_at(.vars = vars(ends_with("_med")),
            .funs = funs(sub("_med", "", .)))
```

```{r}
#calculate se
a_se <- a_data %>% 
  select(source:sample, c(11:91)) %>% 
  group_by(source) %>% 
  mutate_at(c(3:83), list(se = function(x) sd(x) / sqrt(length(x)))) %>% 
  ungroup() %>% 
  select(source:sample, contains("se")) %>% 
  distinct() %>% 
  rename_at(.vars = vars(ends_with("_se")),
            .funs = funs(sub("_se", "", .)))

#combine median and se data and melt for plotting
a_pivot <- a_med %>% 
  pivot_longer(c(3:83), names_to = "wl", values_to = "a" ) %>%
  mutate_at(vars(a), as.numeric) %>% 
  bind_cols(., 
            a_se %>% 
  pivot_longer(c(3:83), names_to = "wl", values_to = "se" ) %>%
  mutate_at(vars(se), as.numeric) %>% select(-source, -sample, -wl)) %>% 
  mutate_at(vars(wl), as.numeric)

```
 
## corrections to derive ap 

```{r}
corrected_a <- a_pivot %>% 
  filter(sample %in% c("discrete a filtrate", "a cal 5", "a whole")) %>% 
  mutate(total_a = ifelse(sample == "a whole", a, NA),
         cdom_a = ifelse(sample == "discrete a filtrate", a, NA),
         water_a = ifelse(sample == "a cal 5", a, NA),
         se_total_a = ifelse(sample == "a whole", se, NA)) %>% 
  group_by(wl) %>% 
  fill(c(total_a, cdom_a, water_a, se_total_a), .direction = "updown") %>% 
  ungroup() %>% 
  select(wl, total_a, cdom_a, water_a, se_total_a) %>% 
  mutate(ap = total_a - cdom_a - water_a)
  
```


## plot

```{r}
corrected_a %>%
  rename(se = se_total_a) %>% 
  select(wl, total_a, ap, se) %>% 
  ggplot(aes(x = wl, y = ap)) +
  geom_errorbar(aes(ymin = ap - se, ymax = ap + se), size = 2, width = 0.5) +
  geom_line() +
  geom_line(aes(y = total_a), color = "blue") +
  geom_errorbar(aes(ymin = total_a - se, ymax = total_a + se), size = 2, width = 0.5, color = "blue") +
  labs(x = "wavelength") +
  theme_classic2(20)
  
```

# c

follows process as for a

```{r}
c <- data %>% 
  select(c) %>% 
  mutate(c = str_squish(c)) %>% 
  #remove the brackets
  mutate(c = str_replace_all(c, "\\[|\\]", "")) %>%
  mutate(c = str_squish(c)) %>% 
  separate(c, sep = " ", into = wavelengths) %>% 
  mutate_all(as.numeric)
  
```

```{r}
c_data <- bind_cols(data, c) %>% 
  select(-c, -a) %>% 
  mutate(time = ymd_hms(time)) %>% 
  group_by(source) %>% 
   mutate(interv = interval(first(time), time),
         s = as.numeric(interv),
         min = s/60) %>% 
  select(source:time, interv:min, everything()) %>% 
  ungroup() 
```

## medians and se

```{r}
c_med <- c_data %>% 
  select(source:sample, c(11:91)) %>% 
  group_by(source) %>% 
  mutate_at(c(3:83), list(med = median)) %>% 
  ungroup() %>% 
  select(source:sample, contains("med")) %>% 
  distinct() %>% 
  rename_at(.vars = vars(ends_with("_med")),
            .funs = funs(sub("_med", "", .)))
```


```{r}
c_se <- c_data %>% 
  select(source:sample, c(11:91)) %>% 
  group_by(source) %>% 
  mutate_at(c(3:83), list(se = function(x) sd(x) / sqrt(length(x)))) %>% 
  ungroup() %>% 
  select(source:sample, contains("se")) %>% 
  distinct() %>% 
  rename_at(.vars = vars(ends_with("_se")),
            .funs = funs(sub("_se", "", .)))

c_pivot <- c_med %>% 
  pivot_longer(c(3:83), names_to = "wl", values_to = "c" ) %>%
  mutate_at(vars(c), as.numeric) %>% 
  bind_cols(., 
            c_se %>% 
  pivot_longer(c(3:83), names_to = "wl", values_to = "se" ) %>%
  mutate_at(vars(se), as.numeric) %>% select(-source, -sample, -wl)) %>% 
  mutate_at(vars(wl), as.numeric)

```

## corrections to derive cp

```{r}
corrected_c <- c_pivot %>% 
  filter(sample %in% c("discrete c filtrate", "c cal 6", "c whole")) %>% 
  mutate(total_c = ifelse(sample == "c whole", c, NA),
         cdom_c = ifelse(sample == "discrete c filtrate", c, NA),
         water_c = ifelse(sample == "c cal 6", c, NA),
         se_total_c = ifelse(sample == "c whole", se, NA)) %>% 
  group_by(wl) %>% 
  fill(c(total_c, cdom_c, water_c, se_total_c), .direction = "updown") %>% 
  ungroup() %>% 
  select(wl, total_c, cdom_c, water_c, se_total_c) %>% 
  mutate(cp = total_c - cdom_c - water_c)
  
```

# b uncorrected

```{r}
b <- left_join(corrected_a %>% select(wl, ap), corrected_c %>% select(wl, cp)) %>% 
  mutate(b = cp - ap)
```


## plot

```{r}
b %>%
  ggplot(aes(x = wl, y = b)) +
  geom_line() +
  labs(x = "wavelength") +
  theme_classic2(20)
  
```









